### ISSUE TITLE
[BUG] Segmentation fault with youtube stream

### ISSUE THREAD

**Issue by Flashwalker** [coslyk/moonplayer#106] opened 2021-01-29 17:03 UTC
**Describe the bug**

Segfault during the attempt to play youtube video format 22

**Error output**

```
qrc:/qml/main.qml:237:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/OpenUrlDialog.qml:37:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/TextInputDialog.qml:34:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/main.qml:97:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/MessageDialog.qml:36:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/ConsoleDialog.qml:66:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
```

**To Reproduce**
1. Open moonplayer in terminal
2. Go to 'Playlist'
3. Click on ' ADD > Url...'
4. Enter youtube URL to parse
5. Click on 'OK', wait for parsing
6. Scroll down to '22 - 1280x720 (720) (mp4 )' stream, or other than the first two
7. Select stream  '22 - 1280x720 (720) (mp4 )', or other than the first two
8. Click on 'OK'
9. See segfault error in terminal

**Screenshots**

---

**System information (please complete the following information):**
 - OS: Ubuntu 20.04 (Pop os)
 - Graphic card: Nvidia GT520M (discrete) + Intel HD Graphics (embeded)

**Additional context**

Appimage

**Comment by coslyk** [comment] 2021-01-29 19:25
Can't reproduce. Can you provide the URL that you test with?

**Comment by Flashwalker** [comment] 2021-01-29 20:49
URL: `https://youtu.be/rmnruY4xmGY`

**Comment by coslyk** [comment] 2021-01-29 21:49
Thanks for your report. It's now fixed in the latest commit.

**Closed as completed** 2021-05-08 08:05 UTC
Labels: bug
